# Generated by Django 3.2.3 on 2021-05-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolchart', '0002_auto_20210514_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate_type',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='type',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='certifcate_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_graduation',
        ),
    ]
