# Generated by Django 3.2.3 on 2021-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolchart', '0003_auto_20210517_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='postal_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
