# Generated by Django 3.2.3 on 2021-05-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolchart', '0004_auto_20210517_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_type',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolchart.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.FloatField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='certifcate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolchart.certificate_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolchart.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolchart.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolchart.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_graduation',
            field=models.DateField(auto_now=True),
        ),
    ]
